# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default valüs.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanül', city: cities.first)
# molino
   molino = Menu.create ({ name: 'Molino', description: 'Pizzeria', phone: '02408 / 926118'})
   #Pizza
   MenuItem.create ({ name: 'Pizza Tonno', menu_id: molino.id, description: 'Thunfisch', order_count: 0 , order_number:"7", price: 7.00})
   MenuItem.create ({ name: 'Pizza Tonno klein', menu_id: molino.id, description: 'Thunfisch', order_count: 0 , order_number:"7 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Hawai', menu_id: molino.id, description: 'Schinken, Ananas', order_count: 0 , order_number:"15", price: 6.50})
   MenuItem.create ({ name: 'Pizza Hawai klein', menu_id: molino.id, description: 'Schinken, Ananas', order_count: 0 , order_number:"15 klein", price: 5.50})
   MenuItem.create ({ name: 'Pizza Diavolo', menu_id: molino.id, description: 'Salami, Peperoni, scharf', order_count: 0 , order_number:"9", price: 7.00})
   MenuItem.create ({ name: 'Pizza Diavolo klein', menu_id: molino.id, description: 'Salami, Peperoni, scharf', order_count: 0 , order_number:"9 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Salami', menu_id: molino.id, description: 'Salami', order_count: 0 , order_number:"4", price: 5.50})
   MenuItem.create ({ name: 'Pizza Salami klein', menu_id: molino.id, description: 'Salami', order_count: 0 , order_number:"4 klein", price: 4.50})
   MenuItem.create ({ name: 'Pizza Vulcano', menu_id: molino.id, description: 'Paprika, scharf', order_count: 0 , order_number:"8", price: 5.00})
   MenuItem.create ({ name: 'Pizza Vulcano klein', menu_id: molino.id, description: 'Paprika, scharf', order_count: 0 , order_number:"8 klein", price: 4.00})
   MenuItem.create ({ name: 'Pizza Frutti di Mare', menu_id: molino.id, description: 'Meeresfrüchte, Knoblauch', order_count: 0 , order_number:"48", price: 8.00})
   MenuItem.create ({ name: 'Pizza Frutti di Mare klein', menu_id: molino.id, description: 'Meeresfrüchte, Knoblauch', order_count: 0 , order_number:"48 klein", price: 7.00})
   MenuItem.create ({ name: 'Pizza Esmeralda', menu_id: molino.id, description: 'Thunfisch, Mais, Zwiebeln, Schafskäse', order_count: 0 , order_number:"27", price: 7.00})
   MenuItem.create ({ name: 'Pizza Esmeralda klein', menu_id: molino.id, description: 'Thunfisch, Mais, Zwiebeln, Schafskäse', order_count: 0 , order_number:"27 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Salvatore', menu_id: molino.id, description: 'Champignons, Paprika, scharf', order_count: 0 , order_number:"32", price: 6.90})
   MenuItem.create ({ name: 'Pizza Salvatore klein', menu_id: molino.id, description: 'Champignons, Paprika, scharf', order_count: 0 , order_number:"32 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Valentino', menu_id: molino.id, description: 'Oliven, Kapern, Champignons, Knoblauch', order_count: 0 , order_number:"35", price: 6.90})
   MenuItem.create ({ name: 'Pizza Valentino klein', menu_id: molino.id, description: 'Oliven, Kapern, Champignons, Knoblauch', order_count: 0 , order_number:"35 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Inferno', menu_id: molino.id, description: 'Champignons, Salami, scharf', order_count: 0 , order_number:"14", price: 6.90})
   MenuItem.create ({ name: 'Pizza Inferno klein', menu_id: molino.id, description: 'Champignons, Salami, scharf', order_count: 0 , order_number:"14 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Margharita', menu_id: molino.id, description: 'Tomatensauce, Käse, Oregano', order_count: 0 , order_number:"1", price: 4.00})
   MenuItem.create ({ name: 'Pizza Margharita klein', menu_id: molino.id, description: 'Tomatensauce, Käse, Oregano', order_count: 0 , order_number:"1 klein", price: 3.00})
   MenuItem.create ({ name: 'Pizza Cipolla', menu_id: molino.id, description: 'Zwiebeln', order_count: 0 , order_number:"2", price: 5.00})
   MenuItem.create ({ name: 'Pizza Cipolla klein', menu_id: molino.id, description: 'Zwiebeln', order_count: 0 , order_number:"2 klein", price: 4.00})
   MenuItem.create ({ name: 'Pizza Napoli', menu_id: molino.id, description: 'Sardellen, Kapern, Oliven, Knoblauch', order_count: 0 , order_number:"3", price: 6.00})
   MenuItem.create ({ name: 'Pizza Napoli klein', menu_id: molino.id, description: 'Sardellen, Kapern, Oliven, Knoblauch', order_count: 0 , order_number:"3 klein", price: 5.00})
   MenuItem.create ({ name: 'Pizza Prosciutto', menu_id: molino.id, description: 'Formfl. Vorderschinken', order_count: 0 , order_number:"5", price: 6.00})
   MenuItem.create ({ name: 'Pizza Prosciutto klein', menu_id: molino.id, description: 'Formfl. Vorderschinken', order_count: 0 , order_number:"5 klein", price: 5.00})
   MenuItem.create ({ name: 'Pizza Acciughe', menu_id: molino.id, description: 'Sardellen, Knoblauch', order_count: 0 , order_number:"6", price: 6.00})
   MenuItem.create ({ name: 'Pizza Acciughe klein', menu_id: molino.id, description: 'Sardellen, Knoblauch', order_count: 0 , order_number:"6 klein", price: 5.00})
   MenuItem.create ({ name: 'Pizza Funghi', menu_id: molino.id, description: 'Champignons', order_count: 0 , order_number:"10", price: 5.50})
   MenuItem.create ({ name: 'Pizza Funghi klein', menu_id: molino.id, description: 'Champignons', order_count: 0 , order_number:"10 klein", price: 4.50})
   MenuItem.create ({ name: 'Pizza Spinaci', menu_id: molino.id, description: 'Spinat, Knoblauch', order_count: 0 , order_number:"11", price: 5.50})
   MenuItem.create ({ name: 'Pizza Spinaci klein', menu_id: molino.id, description: 'Spinat, Knoblauch', order_count: 0 , order_number:"11 klein", price: 4.50})
   MenuItem.create ({ name: 'Pizza Contandia', menu_id: molino.id, description: 'Champignons, Artischocken, Peperoni, scharf', order_count: 0 , order_number:"12", price: 7.00})
   MenuItem.create ({ name: 'Pizza Contandia klein', menu_id: molino.id, description: 'Champignons, Artischocken, Peperoni, scharf', order_count: 0 , order_number:"12 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Campagnola', menu_id: molino.id, description: 'Salami, Sardellen, Kapern', order_count: 0 , order_number:"13", price: 6.90})
   MenuItem.create ({ name: 'Pizza Campagnola klein', menu_id: molino.id, description: 'Salami, Sardellen, Kapern', order_count: 0 , order_number:"13 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Rustica', menu_id: molino.id, description: 'Champignons, Formfl. Vorderschinken, Paprika', order_count: 0 , order_number:"16", price: 6.90})
   MenuItem.create ({ name: 'Pizza Rustica klein', menu_id: molino.id, description: 'Champignons, Formfl. Vorderschinken, Paprika', order_count: 0 , order_number:"16 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Tricolore', menu_id: molino.id, description: 'Spinat, Zwiebeln, Paprika', order_count: 0 , order_number:"17", price: 6.50})
   MenuItem.create ({ name: 'Pizza Tricolore klein', menu_id: molino.id, description: 'Spinat, Zwiebeln, Paprika', order_count: 0 , order_number:"17 klein", price: 5.50})
   MenuItem.create ({ name: 'Pizza O Sole mio', menu_id: molino.id, description: 'Zwiebeln, Spinat, Ei', order_count: 0 , order_number:"18", price: 6.90})
   MenuItem.create ({ name: 'Pizza O Sole mio klein', menu_id: molino.id, description: 'Zwiebeln, Spinat, Ei', order_count: 0 , order_number:"18 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Calabrese', menu_id: molino.id, description: 'Thunfisch, Zwiebeln', order_count: 0 , order_number:"19", price: 7.00})
   MenuItem.create ({ name: 'Pizza Calabrese klein', menu_id: molino.id, description: 'Thunfisch, Zwiebeln', order_count: 0 , order_number:"19 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Mista', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Thunfisch, Salami', order_count: 0 , order_number:"20", price: 7.50})
   MenuItem.create ({ name: 'Pizza Mista klein', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Thunfisch, Salami', order_count: 0 , order_number:"20 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Capricciosa', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Thunfisch, Artischocken', order_count: 0 , order_number:"21", price: 7.50})
   MenuItem.create ({ name: 'Pizza Capricciosa klein', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Thunfisch, Artischocken', order_count: 0 , order_number:"21 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Montanara', menu_id: molino.id, description: 'Spinat, Zwiebeln, Schafskäse, Knoblauch', order_count: 0 , order_number:"22", price: 6.90})
   MenuItem.create ({ name: 'Pizza Montanara klein', menu_id: molino.id, description: 'Spinat, Zwiebeln, Schafskäse, Knoblauch', order_count: 0 , order_number:"22 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Broccoli', menu_id: molino.id, description: 'Brokkoli, Knoblauch', order_count: 0 , order_number:"23", price: 6.50})
   MenuItem.create ({ name: 'Pizza Broccoli klein', menu_id: molino.id, description: 'Brokkoli, Knoblauch', order_count: 0 , order_number:"23 klein", price: 5.50})
   MenuItem.create ({ name: 'Pizza Celine', menu_id: molino.id, description: 'Zwiebeln, Champignongs, Paprika', order_count: 0 , order_number:"24", price: 6.50})
   MenuItem.create ({ name: 'Pizza Celine klein', menu_id: molino.id, description: 'Zwiebeln, Champignongs, Paprika', order_count: 0 , order_number:"24 klein", price: 5.50})
   MenuItem.create ({ name: 'Pizza Siciliana', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Zwiebeln', order_count: 0 , order_number:"25", price: 6.90})
   MenuItem.create ({ name: 'Pizza Siciliana klein', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Zwiebeln', order_count: 0 , order_number:"25 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Regina', menu_id: molino.id, description: 'Thunfisch, Champignons', order_count: 0 , order_number:"26", price: 6.90})
   MenuItem.create ({ name: 'Pizza Regina klein', menu_id: molino.id, description: 'Thunfisch, Champignons', order_count: 0 , order_number:"26 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Silana', menu_id: molino.id, description: 'Formfl. Vorderschinken, Zwiebeln, Ei', order_count: 0 , order_number:"28", price: 6.90})
   MenuItem.create ({ name: 'Pizza Silana klein', menu_id: molino.id, description: 'Formfl. Vorderschinken, Zwiebeln, Ei', order_count: 0 , order_number:"28 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Don', menu_id: molino.id, description: 'Mozzarella, frische Tomaten, Basilikum, Olivenöl', order_count: 0 , order_number:"29", price: 7.00})
   MenuItem.create ({ name: 'Pizza Don klein', menu_id: molino.id, description: 'Mozzarella, frische Tomaten, Basilikum, Olivenöl', order_count: 0 , order_number:"29 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Quattro-Formaggi', menu_id: molino.id, description: '4 verschiedene Käsesorten', order_count: 0 , order_number:"30", price: 7.00})
   MenuItem.create ({ name: 'Pizza Quattro-Formaggi klein', menu_id: molino.id, description: '4 verschiedene Käsesorten', order_count: 0 , order_number:"30 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Corsaro', menu_id: molino.id, description: 'Champignons, Paprika, Salami', order_count: 0 , order_number:"31", price: 6.90})
   MenuItem.create ({ name: 'Pizza Corsaro klein', menu_id: molino.id, description: 'Champignons, Paprika, Salami', order_count: 0 , order_number:"31 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza San Remo', menu_id: molino.id, description: 'Artischocken, Formfl. Vorderschinken, Zwiebeln', order_count: 0 , order_number:"33", price: 6.90})
   MenuItem.create ({ name: 'Pizza San Remo klein', menu_id: molino.id, description: 'Artischocken, Formfl. Vorderschinken, Zwiebeln', order_count: 0 , order_number:"33 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Italia', menu_id: molino.id, description: 'Formfl. Vorderschinken, Spinat, Zwiebeln, Knoblauch', order_count: 0 , order_number:"34", price: 6.90})
   MenuItem.create ({ name: 'Pizza Italia klein', menu_id: molino.id, description: 'Formfl. Vorderschinken, Spinat, Zwiebeln, Knoblauch', order_count: 0 , order_number:"34 klein", price: 5.90})
   MenuItem.create ({ name: 'Pizza Sonja', menu_id: molino.id, description: 'Thunfisch, Mais, Ananas, Salami', order_count: 0 , order_number:"36", price: 7.00})
   MenuItem.create ({ name: 'Pizza Sonja klein', menu_id: molino.id, description: 'Thunfisch, Mais, Ananas, Salami', order_count: 0 , order_number:"36 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Del Sud', menu_id: molino.id, description: 'Thunfisch, Paprika, Zwiebeln', order_count: 0 , order_number:"37", price: 7.00})
   MenuItem.create ({ name: 'Pizza Del Sud klein', menu_id: molino.id, description: 'Thunfisch, Paprika, Zwiebeln', order_count: 0 , order_number:"37 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Consenza', menu_id: molino.id, description: 'Champignons, Brokkoli, Spinat, Knoblauch', order_count: 0 , order_number:"38", price: 7.00})
   MenuItem.create ({ name: 'Pizza Consenza klein', menu_id: molino.id, description: 'Champignons, Brokkoli, Spinat, Knoblauch', order_count: 0 , order_number:"38 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Sabin', menu_id: molino.id, description: 'Champignons, Thunfisch, Ananas', order_count: 0 , order_number:"39", price: 7.00})
   MenuItem.create ({ name: 'Pizza Sabin klein', menu_id: molino.id, description: 'Champignons, Thunfisch, Ananas', order_count: 0 , order_number:"39 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Stefano', menu_id: molino.id, description: 'Champignons, Spinat, Formfl. Vorderschinken, Zwiebeln, Knoblauch', order_count: 0 , order_number:"40", price: 7.00})
   MenuItem.create ({ name: 'Pizza Stefano klein', menu_id: molino.id, description: 'Champignons, Spinat, Formfl. Vorderschinken, Zwiebeln, Knoblauch', order_count: 0 , order_number:"40 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Singara', menu_id: molino.id, description: 'Thunfisch, Champignongs, Formfl. Vorderschinken, Artischocken, Paprika', order_count: 0 , order_number:"41", price: 7.50})
   MenuItem.create ({ name: 'Pizza Singara klein', menu_id: molino.id, description: 'Thunfisch, Champignongs, Formfl. Vorderschinken, Artischocken, Paprika', order_count: 0 , order_number:"41 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Te Soro', menu_id: molino.id, description: 'Spinat, Thunfisch, Ei', order_count: 0 , order_number:"42", price: 7.00})
   MenuItem.create ({ name: 'Pizza Te Soro klein', menu_id: molino.id, description: 'Spinat, Thunfisch, Ei', order_count: 0 , order_number:"42 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Catania', menu_id: molino.id, description: 'Champignons, Formfl. Vorderschinken, Zwiebeln, Paprika', order_count: 0 , order_number:"43", price: 7.00})
   MenuItem.create ({ name: 'Pizza Catania klein', menu_id: molino.id, description: 'Champignons, Formfl. Vorderschinken, Zwiebeln, Paprika', order_count: 0 , order_number:"43 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Quatrofogilo', menu_id: molino.id, description: 'Spinat, Zwiebeln, Formfl. Vorderschinken, Salami, Ei', order_count: 0 , order_number:"44", price: 7.50})
   MenuItem.create ({ name: 'Pizza Quatrofogilo klein', menu_id: molino.id, description: 'Spinat, Zwiebeln, Formfl. Vorderschinken, Salami, Ei', order_count: 0 , order_number:"44 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Giuseppe', menu_id: molino.id, description: 'Brokkoli, Artischocken, Oliven, Knoblauch, scharf', order_count: 0 , order_number:"45", price: 7.50})
   MenuItem.create ({ name: 'Pizza Giuseppe klein', menu_id: molino.id, description: 'Brokkoli, Artischocken, Oliven, Knoblauch, scharf', order_count: 0 , order_number:"45 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Molino', menu_id: molino.id, description: 'Champignongs, Thunfisch, Formfl. Vorderschinken, Spinat, Knoblauch, scharf', order_count: 0 , order_number:"46", price: 7.50})
   MenuItem.create ({ name: 'Pizza Molino klein', menu_id: molino.id, description: 'Champignongs, Thunfisch, Formfl. Vorderschinken, Spinat, Knoblauch, scharf', order_count: 0 , order_number:"46 klein", price: 7.50})
   MenuItem.create ({ name: 'Pizza Verdura', menu_id: molino.id, description: 'Gemüse', order_count: 0 , order_number:"47", price: 7.00})
   MenuItem.create ({ name: 'Pizza Verdura klein', menu_id: molino.id, description: 'Gemüse', order_count: 0 , order_number:"47 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Scampi', menu_id: molino.id, description: 'Scampis, Knoblauch', order_count: 0 , order_number:"49", price: 8.00})
   MenuItem.create ({ name: 'Pizza Scampi klein', menu_id: molino.id, description: 'Scampis, Knoblauch', order_count: 0 , order_number:"49 klein", price: 7.00})
   MenuItem.create ({ name: 'Pizza Rucola', menu_id: molino.id, description: 'Rucola, Parmaschinken, Parmesankäse', order_count: 0 , order_number:"50", price: 8.00})
   MenuItem.create ({ name: 'Pizza Rucola klein', menu_id: molino.id, description: 'Rucola, Parmaschinken, Parmesankäse', order_count: 0 , order_number:"50 klein", price: 7.00})
   MenuItem.create ({ name: 'Pizza Pollo', menu_id: molino.id, description: 'Hänchenbrustfilet', order_count: 0 , order_number:"51", price: 7.50})
   MenuItem.create ({ name: 'Pizza Pollo klein', menu_id: molino.id, description: 'Hänchenbrustfilet', order_count: 0 , order_number:"51 klein", price: 6.50})
   MenuItem.create ({ name: 'Pizza Schleckheim', menu_id: molino.id, description: 'Thunfisch, Formfl. Vorderschinken, Zwiebeln, scharf', order_count: 0 , order_number:"52", price: 7.00})
   MenuItem.create ({ name: 'Pizza Schleckheim klein', menu_id: molino.id, description: 'Thunfisch, Formfl. Vorderschinken, Zwiebeln, scharf', order_count: 0 , order_number:"52 klein", price: 6.00})
   MenuItem.create ({ name: 'Pizza Famiglia', menu_id: molino.id, description: 'Thunfisch, Champignons, Formfl. Voderschinken, Salami', order_count: 0 , order_number:"53", price: 13.00})
   MenuItem.create ({ name: 'Pizza Famiglia klein', menu_id: molino.id, description: 'Thunfisch, Champignons, Formfl. Voderschinken, Salami', order_count: 0 , order_number:"53 klein", price: 12.00})
   MenuItem.create ({ name: 'Pizza Calzone', menu_id: molino.id, description: 'gefüllte Pizza, Zutaten nach Wahl', order_count: 0 , order_number:"53.1", price: 8.00})
   MenuItem.create ({ name: 'Pizza Calzone klein', menu_id: molino.id, description: 'gefüllte Pizza, Zutaten nach Wahl', order_count: 0 , order_number:"53.1 klein", price: 7.00})
   MenuItem.create ({ name: 'Pizza Capricciosa', menu_id: molino.id, description: 'Formfl. Vorderschinken, Champignons, Thunfisch, Artischocken, klein', order_count: 0 , order_number:"", price: 6.50})

   #Pasta
   MenuItem.create ({ name: 'Pasta Aglio e Olio', menu_id: molino.id, description: 'Knoblauch, öl, scarf', order_count: 0 , order_number:"54", price: 5.00})
   MenuItem.create ({ name: 'Pasta Napoli', menu_id: molino.id, description: 'Tomatensauce', order_count: 0 , order_number:"55", price: 5.00})
   MenuItem.create ({ name: 'Pasta Bologna', menu_id: molino.id, description: 'Fleischsauce', order_count: 0 , order_number:"56", price: 6.00})
   MenuItem.create ({ name: 'Pasta Siciliana', menu_id: molino.id, description: 'Auberginen, Speck, Tomatensauce', order_count: 0 , order_number:"57", price: 6.00})
   MenuItem.create ({ name: 'Pasta Gorgonzola', menu_id: molino.id, description: 'Gorgonzolakäse, Sahnesauce', order_count: 0 , order_number:"58", price: 6.50})
   MenuItem.create ({ name: 'Pasta Funghi', menu_id: molino.id, description: 'Champignons, Sahnesauce', order_count: 0 , order_number:"59", price: 6.00})
   MenuItem.create ({ name: 'Pasta Puttanesca', menu_id: molino.id, description: 'Oliven, Kapern, Tomatensauce, Knoblauch, scharf', order_count: 0 , order_number:"60", price: 6.00})
   MenuItem.create ({ name: 'Pasta Carbonara', menu_id: molino.id, description: 'Speck, Ei, Sahnesauce', order_count: 0 , order_number:"61", price: 6.50})
   MenuItem.create ({ name: 'Pasta Vongole', menu_id: molino.id, description: 'Babymuscheln, Tomatensauce, Knoblauch', order_count: 0 , order_number:"62", price: 6.90})
   MenuItem.create ({ name: 'Pasta Tonno', menu_id: molino.id, description: 'Thunfisch, Tomatensauce, Knoblauch', order_count: 0 , order_number:"63", price: 6.50})
   MenuItem.create ({ name: 'Pasta Marinara', menu_id: molino.id, description: 'Thunfisch, Kapern, Sahnesauce', order_count: 0 , order_number:"64", price: 7.00})
   MenuItem.create ({ name: 'Pasta Borussia', menu_id: molino.id, description: 'Thunfisch, Speck, Champignons, Tomatensauce', order_count: 0 , order_number:"65", price: 7.00})
   MenuItem.create ({ name: 'Pasta Molino', menu_id: molino.id, description: 'Champignons, Formfl. Vorderschinken, Mais, Tomaten-Sahnesauce', order_count: 0 , order_number:"66", price: 7.00})
   MenuItem.create ({ name: 'Pasta Casareccia', menu_id: molino.id, description: 'Zucchini, Paprika, Tomaten-Sahnesauce', order_count: 0 , order_number:"67", price: 6.50})
   MenuItem.create ({ name: 'Pasta Contadina', menu_id: molino.id, description: 'Sardellen, Kapern, Tomaten-Sahnesauce', order_count: 0 , order_number:"68", price: 6.50})
   MenuItem.create ({ name: 'Pasta Broccoli', menu_id: molino.id, description: 'Brokkoli, Tomaten-Sahnesauce', order_count: 0 , order_number:"69", price: 6.50})
   MenuItem.create ({ name: 'Pasta Päsana', menu_id: molino.id, description: 'Paprika, Champignons, Erbsen, Tomaten-Sahnesauce', order_count: 0 , order_number:"70", price: 6.50})
   MenuItem.create ({ name: 'Pasta Rabiata', menu_id: molino.id, description: 'Formfl. Vorderschinken, Oliven, Tomatensauce, scharf', order_count: 0 , order_number:"71", price: 6.50})
   MenuItem.create ({ name: 'Pasta Diavolo', menu_id: molino.id, description: 'Krabben, Speck, Tomatensauce, scharf', order_count: 0 , order_number:"72", price: 7.00})
   MenuItem.create ({ name: 'Pasta Chef', menu_id: molino.id, description: 'Forfml. Vorderschinken, Sahnesauce', order_count: 0 , order_number:"73", price: 6.00})
   MenuItem.create ({ name: 'Pasta Pfifferling', menu_id: molino.id, description: 'Pfifferlinge, Sahnesauce', order_count: 0 , order_number:"74", price: 6.50})
   MenuItem.create ({ name: 'Pasta Venezia', menu_id: molino.id, description: 'Scampis, Brokkoli, Tomatensauce, Knoblauch', order_count: 0 , order_number:"75", price: 7.50})
   MenuItem.create ({ name: 'Pasta Casa Nova', menu_id: molino.id, description: 'Hähnchenbrustfilet, Champignons, Tomatensauce,', order_count: 0 , order_number:"76", price: 7.00})
   MenuItem.create ({ name: 'Pasta Panna', menu_id: molino.id, description: 'Sahnesauce', order_count: 0 , order_number:"77", price: 5.00})
   MenuItem.create ({ name: 'Pasta Spinaci', menu_id: molino.id, description: 'Spinat, Sahnesauce, Knoblauch', order_count: 0 , order_number:"78", price: 6.50})
   MenuItem.create ({ name: 'Pasta Rimini', menu_id: molino.id, description: 'Champignons, Forfml. Vorderschinken, Sahnesauce', order_count: 0 , order_number:"79", price: 6.50})
   MenuItem.create ({ name: 'Pasta Salmone', menu_id: molino.id, description: 'Lachsstreifen, Paprika, Zucchini, Tomaten-Sahnesauce', order_count: 0 , order_number:"79.1", price: 8.00})
   MenuItem.create ({ name: 'Pasta Frutti di Mare', menu_id: molino.id, description: 'Meeresfrüchte, Tomatensauce, Knoblauch', order_count: 0 , order_number:"79.2", price: 8.00})
   MenuItem.create ({ name: 'Pasta Mediterano', menu_id: molino.id, description: 'Scampi, Sahnesauce, Knoblauch', order_count: 0 , order_number:"79.3", price: 8.00})
   
   #Tortellini
   MenuItem.create ({ name: 'Tortellini Napoli', menu_id: molino.id, description: 'Tomatensauce', order_count: 0 , order_number:"80", price: 6.00})
   MenuItem.create ({ name: 'Tortellini Bologna', menu_id: molino.id, description: 'Fleischsauce', order_count: 0 , order_number:"81", price: 6.50})
   MenuItem.create ({ name: 'Tortellini Verdi', menu_id: molino.id, description: 'Spinat, Sahnesauce, Knoblauch', order_count: 0 , order_number:"82", price: 6.90})
   MenuItem.create ({ name: 'Tortellini Panna', menu_id: molino.id, description: 'Sahnesauce', order_count: 0 , order_number:"83", price: 6.00})
   MenuItem.create ({ name: 'Tortellini Carbonara', menu_id: molino.id, description: 'Speck, Ei, Sahnesauce', order_count: 0 , order_number:"84", price: 7.00})
   MenuItem.create ({ name: 'Tortellini Chef', menu_id: molino.id, description: 'Formfl. Vorderschinken, Sahnesauce', order_count: 0 , order_number:"85", price: 7.00})
   MenuItem.create ({ name: 'Tortellini Casarecia', menu_id: molino.id, description: 'Zucchini, Paprika, Tomaten-Sahnesauce', order_count: 0 , order_number:"86", price: 7.00})
   MenuItem.create ({ name: 'Tortellini Rabiata', menu_id: molino.id, description: 'Formfl. Vorderschinken, Oliven, Tomatensauce, scharf', order_count: 0 , order_number:"87", price: 7.00})
   MenuItem.create ({ name: 'Tortellini Pfifferling', menu_id: molino.id, description: 'Pfifferlinge, Sahnesauce', order_count: 0 , order_number:"88", price: 7.00})
   
   #Pasta al Forno
   #Nudeln mit Käse überbacken
   MenuItem.create ({ name: 'Tagliatelle 4 Formaggi', menu_id: molino.id, description: 'mit 4 Käsesorten', order_count: 0 , order_number:"89", price: 6.90})
   MenuItem.create ({ name: 'Spaghetti Forno', menu_id: molino.id, description: 'Formfl. Vorderschinken, Ei, Champignons', order_count: 0 , order_number:"90", price: 6.50})
   MenuItem.create ({ name: 'Combinazione', menu_id: molino.id, description: 'Lasagne, Canneloni, Tortellini', order_count: 0 , order_number:"91", price: 6.90})
   MenuItem.create ({ name: 'Cannelloni', menu_id: molino.id, description: 'Nudelrollen mit Fleischfüllung', order_count: 0 , order_number:"92", price: 6.90})
   MenuItem.create ({ name: 'Canelloni Speziale', menu_id: molino.id, description: 'Nudelrollen mit Fleischfüllung und Spinat, Knoblauch', order_count: 0 , order_number:"93", price: 7.00})
   MenuItem.create ({ name: 'Lasagne', menu_id: molino.id, description: '', order_count: 0 , order_number:"94", price: 6.90})
   MenuItem.create ({ name: 'Tortellini', menu_id: molino.id, description: 'Formfl. Vorderschinken, Ei, Champignons', order_count: 0 , order_number:"95", price: 7.50})
   MenuItem.create ({ name: 'Maccheroni Verdura', menu_id: molino.id, description: 'mit Gemüse', order_count: 0 , order_number:"96", price: 6.90})
   
   #Verdura al Forno
   #frisches Gemüse mit Käse überbacken
   MenuItem.create ({ name: 'Zucchini al Forno', menu_id: molino.id, description: 'Zucchini in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"97", price: 6.00})
   MenuItem.create ({ name: 'Carciofi al Forno', menu_id: molino.id, description: 'Artischocken in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"98", price: 6.00})
   MenuItem.create ({ name: 'Aubergine', menu_id: molino.id, description: 'Auberginen in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"99", price: 6.00})
   MenuItem.create ({ name: 'Broccoli al Forno', menu_id: molino.id, description: 'Brokkoli in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"100", price: 6.00})
   MenuItem.create ({ name: 'Funghi al Forno', menu_id: molino.id, description: 'Champignons in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"101", price: 6.50})
   MenuItem.create ({ name: 'Spinaci al Forno', menu_id: molino.id, description: 'Spinat in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"102", price: 6.50})
   MenuItem.create ({ name: 'Peperoni al Forno', menu_id: molino.id, description: 'Paprika in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"103", price: 6.50})
   MenuItem.create ({ name: 'verschiedene Gemüsesorten', menu_id: molino.id, description: 'in Sahnesauce, Tomaten, Knoblauch', order_count: 0 , order_number:"104", price: 6.50})
   MenuItem.create ({ name: 'Funghi speziale', menu_id: molino.id, description: 'Champignons in Sahnesauce, Formfl. Vorderschinken, Tomaten, Knoblauch', order_count: 0 , order_number:"105", price: 7.00})
   
   #Patata al Forno
   #Kartoffelgerichte mit Käse überbacken
   MenuItem.create ({ name: 'Patata Toscana', menu_id: molino.id, description: 'Gorgonzola, Formfl. Vorderschinken', order_count: 0 , order_number:"106", price: 6.90})
   MenuItem.create ({ name: 'Patata Sizillia', menu_id: molino.id, description: 'Spinat, Sahnesauce, Knoblauch', order_count: 0 , order_number:"107", price: 6.90})
   MenuItem.create ({ name: 'Patata Speziale', menu_id: molino.id, description: 'Formfl. Vorderschinken, Sahnesauce, Fleischsauce, Ei', order_count: 0 , order_number:"108", price: 6.90})
   MenuItem.create ({ name: 'Patata Molino', menu_id: molino.id, description: 'Champignons, Artischocken, Tomaten, Paprika, Knoblauch', order_count: 0 , order_number:"109", price: 6.90})
   MenuItem.create ({ name: 'Patata Bolognia', menu_id: molino.id, description: 'Fleischsauce', order_count: 0 , order_number:"110", price: 6.90})
   
   #Carne
   MenuItem.create ({ name: 'Scaloppina al Curry', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Sahnesauce und Currygewürz', order_count: 0 , order_number:"111", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina al Pepe Verde', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit grünem Pfeffer', order_count: 0 , order_number:"112", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina al Pepe Rosso', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit rotem Pfeffer', order_count: 0 , order_number:"113", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina Funghi', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Champignons und Sahnesauce', order_count: 0 , order_number:"114", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina Hawaii', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Ananas, Formfl. Vorderschinken, Käse und Sahnesauce', order_count: 0 , order_number:"115", price: 9.90})
   MenuItem.create ({ name: 'Scaloppina Gorgonzola', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Sahnesauce und Gorgonzolakäse', order_count: 0 , order_number:"116", price: 9.90})
   MenuItem.create ({ name: 'Scaloppina alla Milanese', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Wiener Schnitzel paniert', order_count: 0 , order_number:"117", price: 9.00})
   MenuItem.create ({ name: 'Scaloppina Veronese', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Pfifferlingen, Zwiebeln und Sahnesauce', order_count: 0 , order_number:"118", price: 9.90})
   MenuItem.create ({ name: 'Scaloppina Molino', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Champignons, Speck, Krabben und Sahnesauce', order_count: 0 , order_number:"119", price: 12.50})
   MenuItem.create ({ name: 'Scaloppina Panna', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Sahnesauce', order_count: 0 , order_number:"120", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina Diavolo', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Champignons, Krabben und Tomatensauce, scharf!', order_count: 0 , order_number:"121", price: 10.50})
   MenuItem.create ({ name: 'Scaloppina Cipolatta', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; mit Zwiebeln und Weißweinsauce', order_count: 0 , order_number:"122", price: 9.50})
   MenuItem.create ({ name: 'Scaloppina al Senape', menu_id: molino.id, description: '3 kleine Schnitzel vom Schwein mit Pommes Frites, Kroketten oder Nudeln; in Senf-Sahnesauce', order_count: 0 , order_number:"123", price: 9.50})
   
   #Insalata
   MenuItem.create ({ name: 'Insalata Verde', menu_id: molino.id, description: 'mit grünem Salat und Joghurtdressing', order_count: 0 , order_number:"124", price: 3.00})
   MenuItem.create ({ name: 'Gurkensalat', menu_id: molino.id, description: 'mit Gurken und Joghurtdressing', order_count: 0 , order_number:"125", price: 3.50})
   MenuItem.create ({ name: 'Karottensalat', menu_id: molino.id, description: 'mit Möhren und Joghurtdressing', order_count: 0 , order_number:"126", price: 3.50})
   MenuItem.create ({ name: 'Insalata Pomodori', menu_id: molino.id, description: 'mit Tomaten und Joghurtdressing', order_count: 0 , order_number:"127", price: 3.50})
   MenuItem.create ({ name: 'Kleiner gemischter Salat', menu_id: molino.id, description: 'mit Joghurtdressing', order_count: 0 , order_number:"128", price: 2.00})
   MenuItem.create ({ name: 'Insalata Mista', menu_id: molino.id, description: 'mit Tomaten, Gurken, Joghurtdressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"129", price: 4.10})
   MenuItem.create ({ name: 'Insalata Prima Vera', menu_id: molino.id, description: 'mit Oliven, Zwiebeln, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"130,", price: 4.90})
   MenuItem.create ({ name: 'Insalata Parmigiana', menu_id: molino.id, description: 'mit Käse, Joghurtdressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"131", price: 5.00})
   MenuItem.create ({ name: 'Insalata 4 Formaggi', menu_id: molino.id, description: 'mit 4 Käsesorten, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"132", price: 6.90})
   MenuItem.create ({ name: 'Insalata Hawaii', menu_id: molino.id, description: 'mit Ananas, Formfl. Vorderschinken, Käse, Cocktaildressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"134", price: 6.50})
   MenuItem.create ({ name: 'Insalata Pasticciata', menu_id: molino.id, description: 'mit Formfl. Vorderschinken, Ei, Thunfisch, Cocktaildressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"135", price: 6.50})
   MenuItem.create ({ name: 'Insalata Tonno', menu_id: molino.id, description: 'mit Thunfisch, Zwiebeln, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"136", price: 6.50})
   MenuItem.create ({ name: 'Insalata Nicoise', menu_id: molino.id, description: 'mit Thunfisch, Ei, Joghurtdressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"137", price: 6.50})
   MenuItem.create ({ name: 'Insalata Capricciosa', menu_id: molino.id, description: 'mit Thunfisch, Formfl. Vorderschinken, Käse, Joghurtdressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"138", price: 6.90})
   MenuItem.create ({ name: 'Insalata Forestale', menu_id: molino.id, description: 'mit Ei, Champignons, Zwiebeln, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"139", price: 6.50})
   MenuItem.create ({ name: 'Insalata Marinara', menu_id: molino.id, description: 'mit Thunfisch, Krabben, Zwiebeln, Cocktaildressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"140", price: 7.50})
   MenuItem.create ({ name: 'Insalata Riviera', menu_id: molino.id, description: 'mit Meeresfrüchten, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"141", price: 7.50})
   MenuItem.create ({ name: 'Insalata Verdura', menu_id: molino.id, description: 'mit verschiedenen Gemüsesorten, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"142", price: 6.90})
   MenuItem.create ({ name: 'Insalata Molino', menu_id: molino.id, description: 'mit Karotten, Oliven, Mais, Zwiebeln, Mozzarella, Ei, Paprika, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"143", price: 7.50})
   MenuItem.create ({ name: 'Insalata Pomodoro', menu_id: molino.id, description: 'mit Tomatenscheiben, Mozzarella, Basilikum, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"144", price: 6.90})
   MenuItem.create ({ name: 'Insalata Pollo', menu_id: molino.id, description: 'mit Rucola, Hähnchenbrustfilet, Balsamicössig, Olivenöl, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"145", price: 7.50})
   MenuItem.create ({ name: 'Insalata Rucola', menu_id: molino.id, description: 'mit Rucola, Parmesankäse, Walnüsse, Balsamicössig, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"146", price: 6.90})
   MenuItem.create ({ name: 'Insalata Esmeralda', menu_id: molino.id, description: 'mit Thunfisch, Mais, Zwiebeln, Schafskäse, Joghurtdressing, 4 Pizzabrötchen und Kräuterbutter', order_count: 0 , order_number:"147", price: 6.90})
   
   #Pizzabrötchen
   MenuItem.create ({ name: 'Pizzabrötchen (6 Stück)', menu_id: molino.id, description: 'mit Kräuterbutter', order_count: 0 , order_number:"166", price: 1.90})
   MenuItem.create ({ name: 'Gefüllte Pizzabrötchen (6 Stück)', menu_id: molino.id, description: 'Thunfisch, Käse', order_count: 0 , order_number:"167", price: 3.50})
   MenuItem.create ({ name: 'Gefüllte Pizzabrötchen (6 Stück)', menu_id: molino.id, description: 'Vorderschinken, Käse', order_count: 0 , order_number:"168", price: 3.50})
   MenuItem.create ({ name: 'Gefüllte Pizzabrötchen (6 Stück)', menu_id: molino.id, description: 'Spinat, Schafskäse', order_count: 0 , order_number:"169", price: 4.50})
   
   #Dessert
   MenuItem.create ({ name: 'Tiramisu', menu_id: molino.id, description: 'Caffe-Mascarpone-Eiscremespeise', order_count: 0 , order_number:"", price: 4.00})
   MenuItem.create ({ name: 'Panna Cotta', menu_id: molino.id, description: 'Sahnepudding mit Karamell oder Schokosauce', order_count: 0 , order_number:"", price: 4.00})
   MenuItem.create ({ name: 'Profiterol', menu_id: molino.id, description: 'Windbeutel mit Cremefüllung', order_count: 0 , order_number:"", price: 4.00})
   
   #Getränke inkl. Pfand
   MenuItem.create ({ name: 'Coca Cola 1l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Coca Cola Light 1l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Fanta 1l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Sprite 1l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Bitburger 0,5l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Früh Kölsch 0,5l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Vita Malz 0,5l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Rotwein 0,75l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 8.00})
   MenuItem.create ({ name: 'Weisswein 0,75l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 8.00})
   MenuItem.create ({ name: 'Rosé 0,75l', menu_id: molino.id, description: '', order_count: 0 , order_number:"", price: 8.00})

# delahaye
   delahaye = Menu.create ({ name: 'Delahaye', description: 'Schnellimbiss', phone: '02408 / 80743'})
   MenuItem.create ({ name: 'Kalifornisches Schnitzel-Wunder', menu_id: delahaye.id, description: 'Ananas, Pfirsich, Rahm überbacken', order_count: 0 , order_number:"", price: 5.40})
   MenuItem.create ({ name: 'Rahm-Schnitzel', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 4.60})
   MenuItem.create ({ name: 'Pfeffer-Rahm-Schnitzel', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 5.40})
   MenuItem.create ({ name: 'Prager-Schnitzel', menu_id: delahaye.id, description: 'Schinken, Käse, Rahm überbacken', order_count: 0 , order_number:"", price: 5.40})
   MenuItem.create ({ name: 'Jäger-Schnitzel', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 4.60})
   MenuItem.create ({ name: 'Zigeuner-Schnitzel', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 4.60})
   MenuItem.create ({ name: 'Zwiebel-Schnitzel', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 5.40})
   MenuItem.create ({ name: 'Züricher-Schnitzel', menu_id: delahaye.id, description: 'Champignons, Zwiebeln, Käse überbacken', order_count: 0 , order_number:"", price: 5.40})
   MenuItem.create ({ name: 'Wiener Schnitzel', menu_id: delahaye.id, description: 'vom Schwein', order_count: 0 , order_number:"", price: 3.90})
   MenuItem.create ({ name: 'Italienische Salatschüssel', menu_id: delahaye.id, description: 'Dressing: Joghurt, Kräuter, Öl, Essig, Cocktail', order_count: 0 , order_number:"", price: 4.10})
   MenuItem.create ({ name: 'Kraut-, Gurken- oder Bohnen-Salat', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Kartoffel- oder Nudel-Salat', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.00})
   MenuItem.create ({ name: 'Sahne-Hering-Filets', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 3.00})
   MenuItem.create ({ name: 'Gegrillte Haxe', menu_id: delahaye.id, description: 'täglich frisch', order_count: 0 , order_number:"", price: 3.95})
   MenuItem.create ({ name: 'saurerbraten mit Pommes', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 8.00})
   MenuItem.create ({ name: 'saurerbraten mit Klößen und Rotkohl', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 9.00})
   MenuItem.create ({ name: '1/2 Hähnchen', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 3.30})
   MenuItem.create ({ name: 'Fleischermeister-Frikadelle', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.70})
   MenuItem.create ({ name: 'Hamburger', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.90})
   MenuItem.create ({ name: 'Bratwurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.00})
   MenuItem.create ({ name: 'Bockwurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.00})
   MenuItem.create ({ name: 'Curry-Wurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.80})
   MenuItem.create ({ name: 'Zigeuner-Wurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.80})
   MenuItem.create ({ name: 'Jäger-Wurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.80})
   MenuItem.create ({ name: 'Gyros mit Pommes und Salat', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 7.20})
   MenuItem.create ({ name: 'Pita-Gyros', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 3.50})
   MenuItem.create ({ name: 'Pita Gyros überbacken mit Käse', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 4.50})
   MenuItem.create ({ name: 'Mettwurst', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.10})
   MenuItem.create ({ name: 'Bratrolle', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.30})
   MenuItem.create ({ name: 'Bratrolle Spezial', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.30})
   MenuItem.create ({ name: 'Schaschlik', menu_id: delahaye.id, description: 'pro Portion:', order_count: 0 , order_number:"", price: 3.70})
   MenuItem.create ({ name: 'Frühlingsrolle', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Chicken-Nuggets', menu_id: delahaye.id, description: 'mit Dip', order_count: 0 , order_number:"", price: 2.70})
   MenuItem.create ({ name: 'Gemüsefrikadelle', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.70})
   MenuItem.create ({ name: 'Gemüse-Kartoffel-Gratin', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 4.90})
   MenuItem.create ({ name: 'Frische Reibekuchen (Nur Donnerstags)', menu_id: delahaye.id, description: 'mit Apfelmus, 3 Stück', order_count: 0 , order_number:"", price: 3.00})
   MenuItem.create ({ name: 'Frischer Backfisch (Nur Freitags)', menu_id: delahaye.id, description: 'Seelachs', order_count: 0 , order_number:"", price: 3.80})
   MenuItem.create ({ name: 'Pommes frites', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Pommes frites klein', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.50})
   MenuItem.create ({ name: 'Nudeln', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.40})
   MenuItem.create ({ name: 'Kartoffel-Gratin', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.20})
   MenuItem.create ({ name: 'Reis', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.40})
   MenuItem.create ({ name: 'Kartoffelkroketten', menu_id: delahaye.id, description: '10 Stück', order_count: 0 , order_number:"", price: 1.80})
   MenuItem.create ({ name: 'Bratkartoffelkroketten', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.10})
   MenuItem.create ({ name: 'Folienkartoffeln', menu_id: delahaye.id, description: 'mit Kräuterquark', order_count: 0 , order_number:"", price: 2.80})
   MenuItem.create ({ name: 'Bami', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.20})
   MenuItem.create ({ name: 'Feinmehlkrokette', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 1.10})
   MenuItem.create ({ name: 'Wedges Kartoffelspalten', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 2.00})
   MenuItem.create ({ name: 'Jäger-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.60})
   MenuItem.create ({ name: 'Zigeuner-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.60})
   MenuItem.create ({ name: 'Rahm-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.60})
   MenuItem.create ({ name: 'Curry-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.40})
   MenuItem.create ({ name: 'Schaschlik-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.40})
   MenuItem.create ({ name: 'Sauce Bernaise', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.80})
   MenuItem.create ({ name: 'Pfeffer-Rahm-Soße', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.80})
   MenuItem.create ({ name: 'Salat-Mayonaise', menu_id: delahaye.id, description: '', order_count: 0 , order_number:"", price: 0.40})
   MenuItem.create ({ name: 'Cola, Limo', menu_id: delahaye.id, description: '033 l, ohne Pfand', order_count: 0 , order_number:"", price: 1.20})
   MenuItem.create ({ name: 'Cola, Limo', menu_id: delahaye.id, description: '0.5 l, ohne Pfand', order_count: 0 , order_number:"", price: 1.50})
   MenuItem.create ({ name: 'Cola, Limo', menu_id: delahaye.id, description: '1 l, ohne Pfand', order_count: 0 , order_number:"", price: 2.00})
   MenuItem.create ({ name: 'Bitburger oder König Pilsener', menu_id: delahaye.id, description: '0.5 l, ohne Pfand', order_count: 0 , order_number:"", price: 1.50})

# gia linh
   gia_linh = Menu.create ({ name: 'Gia Linh', description: 'China-Imbiss', phone: '02408 / 928193'})
   MenuItem.create ({ name: 'Frühlingsrolle ohne Fleisch', menu_id: gia_linh.id, description: 'mit süß-saurer Soße', order_count: 0 , order_number:"1", price: 0.90})
   MenuItem.create ({ name: 'Frühlingsrolle mit Fleisch', menu_id: gia_linh.id, description: 'mit süß-saurer Soße', order_count: 0 , order_number:"2", price: 1.10})
   MenuItem.create ({ name: 'Krabbenchips', menu_id: gia_linh.id, description: '3 Stück', order_count: 0 , order_number:"3", price: 1.20})
   MenuItem.create ({ name: 'Schweinefleisch überbacken', menu_id: gia_linh.id, description: 'mit süß-saurer Soße', order_count: 0 , order_number:"4", price: 2.80})
   MenuItem.create ({ name: 'Hühnerfleisch überbacken', menu_id: gia_linh.id, description: 'mit süß-saurer Soße', order_count: 0 , order_number:"6", price: 3.00})
   MenuItem.create ({ name: 'Reis oder gebratene Nudeln', menu_id: gia_linh.id, description: 'als Beilage', order_count: 0 , order_number:"7", price: 1.10})
   MenuItem.create ({ name: 'Gebratener Reis oder gebratene Nudeln', menu_id: gia_linh.id, description: 'mit Schweinefleisch und Sojakeimen', order_count: 0 , order_number:"8", price: 4.40})
   MenuItem.create ({ name: 'Gebratener Reis oder gebratene Nudeln', menu_id: gia_linh.id, description: 'mit Hühnerfleisch und Sojakeimen', order_count: 0 , order_number:"9", price: 4.60})
   MenuItem.create ({ name: 'Bami Goreng Spezial', menu_id: gia_linh.id, description: 'Gebratene Nudeln mit Curry, Hühnerfleisch, Garnelen, Eiern und Sojakeimen', order_count: 0 , order_number:"A9", price: 5.20})
   MenuItem.create ({ name: 'Nasi Goreng Spezial', menu_id: gia_linh.id, description: 'Gebratener Reis mit Curry, Garnelen, Eiern und Sojakeimen', order_count: 0 , order_number:"B9", price: 5.20})
   MenuItem.create ({ name: 'Bami Goreng Ente knusprig', menu_id: gia_linh.id, description: 'Gebratene Nudeln mit Curry, Ente, Eiern und Sojakeimen', order_count: 0 , order_number:"C9", price: 6.40})
   MenuItem.create ({ name: 'Nasi Goreng Ente knusprig', menu_id: gia_linh.id, description: 'Gebratener Reis mit Curry, Ente, Eiern und Sojakeimen', order_count: 0 , order_number:"D9", price: 6.40})
   MenuItem.create ({ name: 'Schweinefleisch Chop-suey', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"10", price: 4.60})
   MenuItem.create ({ name: 'Schweinefleisch Curry', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"11", price: 4.60})
   MenuItem.create ({ name: 'Schweinefleisch Thai-Curry', menu_id: gia_linh.id, description: 'mit Kokosmilch und verschiedenem Gemüse, scharf!', order_count: 0 , order_number:"A11", price: 4.60})
   MenuItem.create ({ name: 'Schweinefleisch mit Sojakeimen', menu_id: gia_linh.id, description: '', order_count: 0 , order_number:"12", price: 4.60})
   MenuItem.create ({ name: 'Schweinefleisch überbacken', menu_id: gia_linh.id, description: 'mit süß-saurer Soße "Spezial" und verschiedenem Gemüse', order_count: 0 , order_number:"13", price: 4.60})
   MenuItem.create ({ name: 'Schweinefleisch natur', menu_id: gia_linh.id, description: 'mit süß-saurer Soße "Spezial" und verschiedenem Gemüse', order_count: 0 , order_number:"A13", price: 4.60})
   MenuItem.create ({ name: 'Hühnerfleisch Chop-suey', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"14", price: 4.80})
   MenuItem.create ({ name: 'Hühnerfleisch Curry', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"15", price: 4.60})
   MenuItem.create ({ name: 'Hühnerfleisch Thai-Curry', menu_id: gia_linh.id, description: 'mit Kokosmilch und verschiedenem Gemüse, scharf!', order_count: 0 , order_number:"A15", price: 4.60})
   MenuItem.create ({ name: 'Hühnerfleisch mit Sojakeimen', menu_id: gia_linh.id, description: '', order_count: 0 , order_number:"16", price: 4.60})
   MenuItem.create ({ name: 'Hühnerfleisch überbacken', menu_id: gia_linh.id, description: 'mit süß-saurer Soße "Spezial" und verschiedenem Gemüse', order_count: 0 , order_number:"17", price: 4.60})
   MenuItem.create ({ name: 'Hühnerfleisch natur', menu_id: gia_linh.id, description: 'mit süß-saurer Soße "Spezial" und verschiedenem Gemüse', order_count: 0 , order_number:"A17", price: 4.60})
   MenuItem.create ({ name: 'Gemischter Teller "Gia Linh"', menu_id: gia_linh.id, description: 'Frühlingsrolle, Chop-suey, Hühnerfleischbällchen, mit süß-saurer Soße', order_count: 0 , order_number:"18", price: 4.80})
   MenuItem.create ({ name: 'Gemischter Teller vegetarisch', menu_id: gia_linh.id, description: 'Frühlingsrolle, Chop-suey, Gemüsebällchen, mit süß-saurer Soße', order_count: 0 , order_number:"19", price: 4.80})
   MenuItem.create ({ name: 'Ente cantonesisch', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse, scharf!', order_count: 0 , order_number:"20", price: 6.40})
   MenuItem.create ({ name: 'Ente Thai-Curry', menu_id: gia_linh.id, description: 'mit Kokosmilch und Gemüse, scharf!', order_count: 0 , order_number:"A20", price: 6.40})
   MenuItem.create ({ name: 'Ente Chop-suey', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"21", price: 6.40})
   MenuItem.create ({ name: 'Ente mit süß-saurer Soße "Spezial"', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"22", price: 6.40})
   MenuItem.create ({ name: 'Ente mit Sojakeimen', menu_id: gia_linh.id, description: '', order_count: 0 , order_number:"A22", price: 6.40})
   MenuItem.create ({ name: 'Tofu Chop-suey', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"23", price: 4.80})
   MenuItem.create ({ name: 'Tofu Curry', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"24", price: 4.80})
   MenuItem.create ({ name: 'Tofu Thai-Curry', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"A24", price: 4.80})
   MenuItem.create ({ name: 'Tofu mit Sojakeimen', menu_id: gia_linh.id, description: '', order_count: 0 , order_number:"25", price: 4.80})
   MenuItem.create ({ name: 'Tofu mit süß-saurer Soße "Spezial"', menu_id: gia_linh.id, description: 'mit verschiedenem Gemüse', order_count: 0 , order_number:"26", price: 4.80})
   MenuItem.create ({ name: 'Überbackenes Gemüse', menu_id: gia_linh.id, description: 'mit süß-saurer Soße "Spezial"', order_count: 0 , order_number:"27", price: 4.80})
   MenuItem.create ({ name: 'Überbackene Bananen', menu_id: gia_linh.id, description: '', order_count: 0 , order_number:"", price: 1.60})
   MenuItem.create ({ name: 'Cola, Fanta, Sprite, Wasser', menu_id: gia_linh.id, description: '0.33 l, ohne Pfand', order_count: 0 , order_number:"", price: 1.00})
   MenuItem.create ({ name: 'Bitburger', menu_id: gia_linh.id, description: '0.33 l, ohne Pfand', order_count: 0 , order_number:"", price: 1.10})
   MenuItem.create ({ name: 'Takara', menu_id: gia_linh.id, description: 'Japanischer Pflaumenwein, 0.75 l, ohne Pfand', order_count: 0 , order_number:"", price: 6.30})
